# Generated by Django 3.2.6 on 2021-08-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='auctions.auction_list'),
        ),
    ]
