# Generated by Django 3.2.6 on 2021-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bids_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='max_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
