# Generated by Django 3.2.6 on 2021-09-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_list_max_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'ordering': ['price']},
        ),
    ]
