# Generated by Django 3.2.6 on 2021-09-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_auction_list_max_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='parent_comment',
        ),
    ]
