# Generated by Django 3.2.6 on 2021-09-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_comments_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='child_comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='auctions.comments'),
        ),
    ]
