# Generated by Django 3.2.6 on 2021-09-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210905_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='child_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='auctions.comments'),
        ),
    ]
