# Generated by Django 3.2.6 on 2021-09-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210905_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
