# Generated by Django 3.2.6 on 2021-09-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210905_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
