# Generated by Django 3.2.6 on 2021-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_replies_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
