# Generated by Django 3.2.6 on 2021-09-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_comments_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
