# Generated by Django 3.2.6 on 2021-09-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auction_list_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_list',
            old_name='status',
            new_name='is_open',
        ),
    ]
